name: month_range_picker_modal
description: A customizable Flutter date picker modal that supports month/year selection and custom date range selection with preset options.
version: 1.0.0
homepage: https://github.com/Ifoegbu1/month_range_picker_modal
repository: https://github.com/Ifoegbu1/month_range_picker_modal
issue_tracker: https://github.com/Ifoegbu1/month_range_picker_modal/issues
documentation: https://github.com/Ifoegbu1/month_range_picker_modal#readme
topics:
  - flutter
  - date-picker
  - month
  - range
  - modal

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
